import Foundation
import Testing

/// The installed agent protocol is the one thing simmer puts on a Mac whose
/// going stale is completely silent. The binary upgrades, `AGENTS.md` moves, and
/// the skill in ~/.claude keeps saying whatever it said the day it was written —
/// agents keep reading it, and nothing anywhere goes red.
///
/// So `make skill` stamps the version it generated from, and `doctor` reports
/// skew. These tests drive the built binary through `SIMMER_SKILL_DIR`, which is
/// why that seam exists: `homeDirectoryForCurrentUser` reads the passwd entry
/// and ignores `HOME`, so without it this suite would inspect the developer's
/// own installed skill and pass or fail on machine state.
@Suite struct AgentProtocolTests {
    /// A skill directory, and the ~/.claude the check requires above it.
    /// Returns the paths and a live `Sim` sharing the same fake home.
    static func withSkill(_ body: (Sim, URL) -> Void) {
        let sim = Sim()
        defer { sim.tearDown() }
        let skillDir = sim.root.appendingPathComponent(".claude/skills/simmer")
        try? FileManager.default.createDirectory(at: skillDir, withIntermediateDirectories: true)
        body(sim, skillDir)
    }

    static func write(_ text: String, to dir: URL) {
        try! text.write(to: dir.appendingPathComponent("SKILL.md"),
                        atomically: true, encoding: .utf8)
    }

    /// doctor honours the seam, so the row comes from the fake home.
    static func doctor(_ sim: Sim, skillDir: URL) -> Sim.Result {
        sim.run(["doctor", "--json"], env: ["SIMMER_SKILL_DIR": skillDir.path])
    }

    static func row(_ result: Sim.Result, id: String) -> [String: Any]? {
        let parsed = (try? JSONSerialization.jsonObject(with: Data(result.out.utf8)))
            as? [String: Any]
        let checks = parsed?["checks"] as? [[String: Any]] ?? []
        return checks.first { $0["id"] as? String == id }
    }

    /// The version simmer reports for itself — whatever `make skill` would
    /// stamp. Read from the binary rather than restated, so a release bump
    /// cannot leave this suite asserting last version's number.
    static func version(_ sim: Sim) -> String {
        let parsed = (try? JSONSerialization.jsonObject(
            with: Data(sim.run(["doctor", "--json"]).out.utf8))) as? [String: Any]
        return parsed?["version"] as? String ?? ""
    }

    /// A protocol generated by this exact binary is current, and says so.
    @Test func aCurrentProtocolReportsGreen() {
        Self.withSkill { sim, dir in
            Self.write("""
                ---
                name: simmer
                ---

                <!-- simmer-protocol version=\(Self.version(sim)) source=AGENTS.md -->

                # Using simmer
                """, to: dir)

            let row = Self.row(Self.doctor(sim, skillDir: dir), id: "agent_protocol")
            #expect(row != nil, "doctor reported no agent_protocol row")
            #expect(row?["ok"] as? Bool == true)
        }
    }

    /// The case the whole exercise exists for: the binary moved on and the
    /// protocol did not. Reported, and reported as out of date rather than
    /// broken — a stale document is not a broken install, and a red row here
    /// would teach people to skim the rest of the report.
    @Test func aStaleProtocolIsReportedWithoutFailingTheReport() {
        Self.withSkill { sim, dir in
            Self.write("""
                <!-- simmer-protocol version=0.0.1-ancient source=AGENTS.md -->

                # Using simmer
                """, to: dir)

            let result = Self.doctor(sim, skillDir: dir)
            let row = Self.row(result, id: "agent_protocol")
            #expect(row?["ok"] is NSNull, "a stale protocol must be informational, not red")
            let label = row?["label"] as? String ?? ""
            // Both versions named: "yours is old" without saying old-relative-
            // to-what is not actionable.
            #expect(label.contains("0.0.1-ancient"), "\(label)")
            #expect(label.contains(Self.version(sim)), "\(label)")
        }
    }

    /// A hand-written or pre-stamp skill: present, unverifiable, and that is
    /// its own diagnosis rather than something to guess about.
    @Test func anUnstampedProtocolSaysSoRatherThanAssumingItIsCurrent() {
        Self.withSkill { sim, dir in
            Self.write("---\nname: simmer\n---\n\n# Using simmer\n", to: dir)

            let row = Self.row(Self.doctor(sim, skillDir: dir), id: "agent_protocol")
            #expect(row?["ok"] is NSNull)
            #expect((row?["label"] as? String ?? "").contains("no version stamp"))
        }
    }

    /// ~/.claude exists but nothing was installed into it — worth a line,
    /// because agents on that Mac silently do not know the rules.
    @Test func aMissingProtocolUnderAnExistingClaudeHomeIsReported() {
        Self.withSkill { sim, dir in
            // The directory exists; the file does not.
            let row = Self.row(Self.doctor(sim, skillDir: dir), id: "agent_protocol")
            #expect(row?["ok"] is NSNull)
            #expect((row?["label"] as? String ?? "").contains("not installed"))
        }
    }

    /// No ~/.claude at all: no row. `make install` never creates that directory,
    /// so a line about a protocol this Mac was never going to have is a line
    /// about nothing — and doctor's whole discipline is that every row earns its
    /// place.
    @Test func noClaudeHomeMeansNoRowAtAll() {
        let sim = Sim()
        defer { sim.tearDown() }

        let absent = sim.root.appendingPathComponent("no-claude-here/skills/simmer")
        let result = sim.run(["doctor", "--json"], env: ["SIMMER_SKILL_DIR": absent.path])

        #expect(Self.row(result, id: "agent_protocol") == nil,
                "doctor invented a row for a ~/.claude that does not exist")
    }

    /// Whatever the protocol row says, it never turns doctor red — the exit code
    /// and `healthy` belong to the install being broken, and a stale document is
    /// not that.
    @Test func theProtocolRowNeverChangesDoctorsVerdict() {
        Self.withSkill { sim, dir in
            let clean = sim.run(["doctor", "--json"])
            Self.write("<!-- simmer-protocol version=0.0.1-ancient -->\n", to: dir)
            let stale = Self.doctor(sim, skillDir: dir)

            let before = (try? JSONSerialization.jsonObject(with: Data(clean.out.utf8)))
                as? [String: Any]
            let after = (try? JSONSerialization.jsonObject(with: Data(stale.out.utf8)))
                as? [String: Any]
            #expect(after?["failures"] as? Int == before?["failures"] as? Int)
            #expect(stale.code == clean.code)
        }
    }
}
